# Generated by Django 5.1.5 on 2025-02-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('fecha', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=50)),
                ('equipo', models.CharField(max_length=50)),
                ('operador', models.CharField(max_length=50)),
                ('ayudante', models.CharField(max_length=50)),
                ('trabajo_realizado', models.TextField()),
                ('hora_salida', models.TimeField()),
                ('hora_llegada', models.TimeField()),
                ('hora_termino', models.TimeField()),
                ('hora_regreso', models.TimeField()),
                ('costo_hora', models.IntegerField()),
                ('total_horas', models.FloatField()),
                ('total_sin_iva', models.FloatField()),
                ('total_con_iva', models.FloatField()),
            ],
        ),
    ]
