# Generated by Django 5.1.5 on 2025-01-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cliente', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=50)),
                ('equipo', models.CharField(max_length=50)),
                ('operador', models.CharField(max_length=50)),
                ('ayudante', models.CharField(max_length=50)),
                ('trabajo_realizado', models.TextField()),
                ('hora_salida', models.TimeField()),
                ('hora_llegada', models.TimeField()),
                ('hora_termino', models.TimeField()),
                ('hora_regreso', models.TimeField()),
                ('horas_trabajo', models.FloatField()),
                ('costo_hora', models.IntegerField()),
                ('costo_maniobra', models.FloatField()),
                ('costo_maniobra_iva', models.FloatField()),
            ],
        ),
    ]
