# Generated by Django 5.1.5 on 2025-02-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas_gruas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='notas_pdfs/'),
        ),
    ]
