# Generated by Django 5.1.5 on 2025-01-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas_gruas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='telefono',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
