# Generated by Django 5.1.5 on 2025-01-30 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas_gruas', '0002_nota_telefono'),
    ]

    operations = [
    ]
