# Generated by Django 5.1.5 on 2025-02-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas_gruas', '0002_nota_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
