<BaseScreen>:
    BoxLayout:
        orientation: "vertical"

        # Barra superior (MDTopAppBar)
        MDTopAppBar:
            title: "Mi App"

        # Contenedor para el contenido de cada pantalla hija
        BoxLayout:
            id: content_box
            orientation: "vertical"

        # Barra inferior (MDToolbar)
        MDToolbar:
            size_hint_y: None
            height: "50dp"
            left_action_items: [["arrow-left", lambda x: app.on_back()]]