# Generated by Django 5.1.5 on 2025-01-29 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cantidad', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ingeniero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingeniero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('ingeniero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos_almacen.ingeniero')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos_almacen.pedido')),
                ('ingeniero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos_almacen.ingeniero')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos_almacen.material')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='pedidos_almacen.pedido')),
            ],
        ),
    ]
