# Generated by Django 5.1.5 on 2025-01-30 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacen', '0001_initial'),
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ingeniero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacion.ingeniero')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almacen.articulo')),
            ],
        ),
    ]
