# Generated by Django 5.1.5 on 2025-01-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_almacen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidomaterial',
            name='ingeniero',
        ),
        migrations.AddField(
            model_name='pedidomaterial',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pedidomaterial',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
